/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2dpbo;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Dicki Fathurohman
 */
public class AddArtist extends javax.swing.JFrame {
     private dbConnection db = new dbConnection(); 
     File f = null;
     private Boolean isUpdate = false;
     private MainFrame panelCard;
     private int id;
     
     private String name;
     private String nationality;
     private String namafoto;
    /**
     * Creates new form AddArtist
     */
    public AddArtist() {
        initComponents();
        
        if(isUpdate == false){
            ButtonSubmit.setText("Add Data");
        }else{
            ButtonSubmit.setText("Update Data");
        }
    }
    
    public AddArtist(MainFrame panelCard, int id){
        initComponents();
        ImageIcon icon = null;
        
        this.panelCard = panelCard;
        this.id = id;
        
        isUpdate = true;
        
        if(isUpdate == false){
            ButtonSubmit.setText("Add Data");
        }else{
            ButtonSubmit.setText("Update Data");
        }
        
        ResultSet res = db.selectQuery("SELECT * FROM artist WHERE id=" +this.id);
        
        try {
            if(res.next()){
                FieldName.setText(res.getString("name"));
                FieldNationality.setText(res.getString("nationality"));

                icon = new ImageIcon("src\\Assets\\"+res.getString("profile"));
                namafoto = res.getString("profile");
                Image image = icon.getImage().getScaledInstance(100, 150, Image.SCALE_SMOOTH);
                ImageIcon ic = new ImageIcon(image);
                LabelProfile.setIcon(ic);
            }
        } catch (SQLException e) {
           JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FieldName = new javax.swing.JTextField();
        FieldNationality = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LabelProfile = new javax.swing.JLabel();
        ButtonUpload = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Nationality");

        LabelProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonUpload.setText("Upload Picture");
        ButtonUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUploadActionPerformed(evt);
            }
        });

        ButtonSubmit.setText("Submit");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Cancel");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(ButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonCancel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ButtonUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ButtonCancel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(FieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FieldNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonUpload))
                    .addComponent(LabelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(ButtonSubmit)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUploadActionPerformed
        // TODO add your handling code here:
       try{
          JFileChooser chooser = new JFileChooser();
          chooser.setAcceptAllFileFilterUsed(false); // Disable the "All Files" option
          chooser.addChoosableFileFilter(new FileNameExtensionFilter("Images (*.jpg, *.jpeg, *.png)", "jpg", "jpeg", "png"));
          chooser.showOpenDialog(null);
          f = chooser.getSelectedFile();
          ImageIcon icon = new ImageIcon(f.toString());
          Image image = icon.getImage().getScaledInstance(LabelProfile.getWidth(), LabelProfile.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon ic = new ImageIcon(image);
          LabelProfile.setIcon(ic);
         
       } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_ButtonUploadActionPerformed

    private void FieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNameActionPerformed
    
    private void getData(){
        name = FieldName.getText();
        nationality = FieldNationality.getText();
        
        if(name.isEmpty() || nationality.isEmpty()){
            JOptionPane.showMessageDialog(null, "Harap isi form yang kosong!");
        }
        else{
            
            String newpath = "src/Assets/";
            File directory = new File(newpath);
            if(!directory.exists()){
                directory.mkdir();
            }
            
            if(f != null){
                String filename = f.getAbsolutePath();
                namafoto = filename.substring(filename.lastIndexOf('\\') + 1);
                File sourceFile = new File(filename);
                Date tanggal_upload = new Date();
                String tampilan = "yyyyMMddhhmmss";
                SimpleDateFormat fm = new SimpleDateFormat(tampilan);
                String tanggal = String.valueOf(fm.format(tanggal_upload));
                File destinationFile = new File(newpath+"/" + tanggal.toString() +"_"+ namafoto);
                String newfile = destinationFile.getAbsolutePath();
                namafoto = newfile.substring(newfile.lastIndexOf('\\') + 1);
                try {
                    Files.copy(sourceFile.toPath(), destinationFile.toPath());
                } catch (IOException ex) {
                    Logger.getLogger(AddArtist.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } 
    }
    private void AddData(){
        
        getData();
        
        
        String sql = "INSERT INTO artist(name, nationality, profile) VALUES ('"+name+"' , '"+nationality+"', '"+namafoto+"')";
        db.updateQuery(sql);

        dispose();
        JOptionPane.showMessageDialog(null, "Add Success!");
        new MainFrame("Artist").setVisible(true);
    }
    
    private void UpdateData(){
        
        getData();
        
       // String sql = "UPDATE artist SET name= '"+name+"' , nationality= '"+nationality+"' , profile=" '"+namafoto+"' "WHERE id =" + this.id;
        String sql = "UPDATE artist SET name='" + name + "', nationality='" + nationality + "', profile='" + namafoto + "' WHERE id=" + this.id;

        int cardDeleted = db.updateQuery(sql);
        if(cardDeleted > 0){
            panelCard.setPanelArtist();
            dispose();
            JOptionPane.showMessageDialog(null, "Data telah diupdate!");
            new MainFrame("Artist").setVisible(true);
        }
        else{
            dispose();
            JOptionPane.showMessageDialog(null, "Data gagal diupdate!");
            new MainFrame("Artist").setVisible(true);
        }
        
        
    }
    
    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSubmitActionPerformed
        // TODO add your handling code here:
        if(isUpdate == false){
            AddData();
        }else{
            UpdateData();
        }
    }//GEN-LAST:event_ButtonSubmitActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame("Artist").setVisible(true);
    }//GEN-LAST:event_ButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddArtist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JButton ButtonUpload;
    private javax.swing.JTextField FieldName;
    private javax.swing.JTextField FieldNationality;
    private javax.swing.JLabel LabelProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
