/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2dpbo;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

import java.sql.ResultSet;
import java.sql.SQLException;
/**
 *
 * @author Dicki Fathurohman
 */
public class MainFrame extends javax.swing.JFrame {
    private String page;
    /**
     * Creates new form NewJFrame
     */
    private dbConnection db;
    
    public MainFrame(){
        initComponents();
        this.db = new dbConnection();
    }
    
    public MainFrame(String page) {
        initComponents();
        this.db = new dbConnection();
        this.page = page;
        
        if(this.page.equals("Artist")){
            LabelTitle.setText("LIST ARTIST");
            ButtonPage.setText("View Album Page");
            ButtonAdd.setText("Add Artist");
            setPanelArtist();
        }
        else{
            LabelTitle.setText("LIST ALBUM");
            ButtonPage.setText("View Artist Page");
            ButtonAdd.setText("Add Album");
            setPanelAlbum();
        }
        
    }
    
    void setPanelArtist() {   
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        DataPanel.removeAll();
        DataPanel.setLayout(new GridLayout(0, 1));
        ArtistCard card;
        ResultSet res = db.selectQuery("SELECT * FROM artist");
        try {
            while (res.next()) {
                card = new ArtistCard(this, res.getInt("id"));
                DataPanel.add(card);
            }
        } catch (SQLException ex) {
//            logger.getLogger(Menu.class.getName()).log();
            System.out.println(ex.getMessage());
        }
        
        DataPanel.revalidate();
        DataPanel.repaint();
    }
    
    void setPanelAlbum() {   
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        DataPanel.removeAll();
        DataPanel.setLayout(new GridLayout(0, 1));
        AlbumCard card;
        ResultSet res = db.selectQuery("SELECT * FROM album");
        try {
            while (res.next()) {
                card = new AlbumCard(this, res.getInt("id_album"));
                DataPanel.add(card);
            }
        } catch (SQLException ex) {
//            logger.getLogger(Menu.class.getName()).log();
            System.out.println(ex.getMessage());
        }
        
        DataPanel.revalidate();
        DataPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DataPanel = new javax.swing.JPanel();
        Blogout = new javax.swing.JButton();
        ButtonAdd = new javax.swing.JButton();
        ButtonPage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelTitle.setText("LIST ARTIST");
        LabelTitle.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LabelTitlePropertyChange(evt);
            }
        });

        javax.swing.GroupLayout DataPanelLayout = new javax.swing.GroupLayout(DataPanel);
        DataPanel.setLayout(DataPanelLayout);
        DataPanelLayout.setHorizontalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        DataPanelLayout.setVerticalGroup(
            DataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(DataPanel);

        Blogout.setText("Logout");
        Blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlogoutActionPerformed(evt);
            }
        });

        ButtonAdd.setText("Add");
        ButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddActionPerformed(evt);
            }
        });

        ButtonPage.setText("View Page");
        ButtonPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPage, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAdd)
                            .addComponent(Blogout))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(Blogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelTitle)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlogoutActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                this.setVisible(false);
                new Login().setVisible(true);
            } else{
                // aksi ketika pengguna memilih tombol No
            }
    }//GEN-LAST:event_BlogoutActionPerformed

    private void ButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        dispose();
        if(this.page.equals("Artist")){
            new AddArtist().setVisible(true);
        }
        else{
            new AddAlbum().setVisible(true);
        }
        
    }//GEN-LAST:event_ButtonAddActionPerformed

    private void LabelTitlePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LabelTitlePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelTitlePropertyChange

    private void ButtonPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPageActionPerformed
        // TODO add your handling code here:
        if(this.page.equals("Artist")){
            dispose();
            new MainFrame("Album").setVisible(true);
        }
        else{
            dispose();
            new MainFrame("Artist").setVisible(true);
        }
    }//GEN-LAST:event_ButtonPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Blogout;
    private javax.swing.JButton ButtonAdd;
    private javax.swing.JButton ButtonPage;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JLabel LabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
